### ISSUE TITLE
Create a "Minting Page" for visitors to mint an NFT or token to become a member of the DAO.

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/create-dao#16]

**Comment by berteotti** [comment]
I can help with the development of this task

**Comment by naz3eh** [comment]
@berteotti Have you made any progress in this? If not I would like to take over

**Comment by berteotti** [comment]
> @berteotti Have you made any progress in this? If not I would like to take over

Sorry @Nazeeh21, I already started it
