### ISSUE TITLE
Create a script that generates a `package.json` file for the template for local development

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/create-dao#18]
At the moment, the template folder does not have a package.json file included in the source code. The package.json is being generated on-the-go by the `create-app.js` script. This is fine for the end-users but makes local development a bit difficult.

The workaround for now is to copy the `package.json` generated by running `npx create-dao` and placing it inside the template folder. (Make sure you don't commit it)

The ideal solution is to have a utility script that generates a package.json file for local development. 

Another possible solution is to store the contents of the `package.json` file in a dummy file (`PACKAGES` - for the sake of an example) and ignoring that file when copying the contents of the template folder inside the script.

**Comment by e-roy** [comment]
I think using workspaces might be the cleanest route

**Comment by Dhaiwat10** [comment]
@e-roy can you help with that, please? I'm not a devops expert

**Comment by Dhaiwat10** [comment]
Closed via #19
