### ISSUE TITLE
private settings in package.json

### ISSUE THREAD

**Issue by e-roy** [Developer-DAO/create-dao#20]
For [publishing to npm](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#private), private must be set to false.

But [workspaces to work properly](https://blog.kintone.io/entry/2020/07/14/103322), private must be set to true.

[Lerna](https://www.npmjs.com/package/lerna) helps solve this problem for monorepos.  

@Dhaiwat10 please assign this to me

**Comment by e-roy** [comment]
@Dhaiwat10 so after looking into this a little bit further, Lerna is awesome for managing multiple packages under one repo.  Currently we only really only have one package in this repo.  I think the answer to this is a bit simpler.

I don't think we even need this line 
` "private": "true",`
https://github.com/Developer-DAO/create-dao/blob/0709815bf658dee5ae747c3591acea46003cb1e1/package.json#L4

I think just deleting this line will solve this issue.  Can you try this and test publishing?

**Comment by Dhaiwat10** [comment]
@e-roy if I remove that line:

a) Yes, I can publish the package to npm.
b) I cannot install the dependencies by running `yarn`. 
```bash
error Workspaces can only be enabled in private projects.
```

**Comment by e-roy** [comment]
@Dhaiwat10 I see.

I've created a test for this [here](https://github.com/e-roy/npx-create-test-v2) for you to see file structure and a working test example.  This has scripts to run for next development, version update, and npm publish.  This will require a huge change in the file structure, but will layout properly for future other packages to be held here in a monorepo.  It wouldn't take too long to do, but since it does have such a huge change, it might be good to clear up any PRs before starting.

The current structure is: 

```
├── helpers
│  ├── git.js
│  ├── install.js
│  └── ...
├── template
│  ├── components
│  │  └── ...
│  ├── contracts
│  │  └── ...
│  ├── pages
│  │  └── ...
│  └──...
├── README.md
├── create-app.js
├── index.js
├── .gitignore
├── package.json
└── ...
```

adding lerna will need this structure

```
├── packages
│  └──create-dao
│  │  ├── helpers
│  │  │  ├── git.js
│  │  │  ├── install.js
│  │  │  └── ...
│  │  ├── template
│  │  │  ├── components
│  │  │  │  └── ...
│  │  │  ├── contracts
│  │  │  │  └── ...
│  │  │  ├── pages
│  │  │  │  └── ...
│  │  │  └──...
│  │  ├── README.md
│  │  ├── create-app.js
│  │  ├── index.js
│  │  ├── .gitignore
│  │  ├── package.json
│  │  └── ...
├── README.md
├── .gitignore
├── lerna.json
└── package.json
```

**Comment by Dhaiwat10** [comment]
@e-roy thanks for trying that out. This looks really promising. Can you put in a PR so that we can test this out?
