### ISSUE TITLE
Remove the static stuff from the mint page

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/create-dao#36]
Right now due to the nature of the `useTransaction` hook, the ether being passed to the transaction is statically set to `0.05 ether`. This should be changed to be dynamic and adaptive to the contract.

We should wait for the `useTransaction` hook to be updated to support passing in params when it is called (https://github.com/Developer-DAO/web3-ui/issues/174).

**Comment by e-roy** [comment]
When [PR](https://github.com/Developer-DAO/create-dao/pull/39) the `useTransaction` hook was removed.  Currently the mint price is updated from the `useContract` hook getting the data from `.cost()` 

```
      const response = await nftContract.mint(1, {
        value: ethers.utils.parseEther(mintPrice),
      });
```
Found [here](https://github.com/Developer-DAO/create-dao/blob/df2a6be70e558cc0474322ce2f20504ab32624ec/packages/create-dao/templates/default/pages/mint.js#L54)

which is the same value as displayed on UI next to the mint button.

@Dhaiwat10 does this resolve this issue, or will there be a need to utilize the `useTransaction` hook instead when it is working properly?

**Comment by Dhaiwat10** [comment]
I think so, closing this one. Thanks!
