### ISSUE TITLE
@web3-ui/core package error

### ISSUE THREAD

**Issue by e-roy** [Developer-DAO/create-dao#38]
I tried npx create-dao today and found an error with using the @web3-ui/core package 0.4.0.  

When using npx create-dao, v 0.4.0 is installed automatically
When using this repo in development, 0.2.0 is in the [package.json](https://github.com/Developer-DAO/create-dao/blob/966bc0c651ec2a8f693b2bcbec8d2b2317afd838/packages/create-dao/templates/default/package.json#L25)

Is this an issue with @web3-ui/core package 0.4.0?

![web3-ui-error](https://user-images.githubusercontent.com/70700747/148809771-5f1fe163-11bf-4376-928c-af5310e74ef1.png)

work around is to lock down the version the user installs to v 0.2.0 [here](https://github.com/Developer-DAO/create-dao/blob/966bc0c651ec2a8f693b2bcbec8d2b2317afd838/packages/create-dao/create-app.js#L95)

`    'framer-motion@^4',
    'react-icons',
    '@web3-ui/core',
  ];
`
to :
`    'framer-motion@^4',
    'react-icons',
    '@web3-ui/core@0.2.0',
  ];
`

@Dhaiwat10 thoughts?

**Comment by with-heart** [comment]
It's a problem with `web3-ui`. It'll be fixed once we merge and publish this: https://github.com/Developer-DAO/web3-ui/pull/217

**Comment by e-roy** [comment]
Since the @web3-ui/core package is still being battle tested, shouldn't the user's version be locked down to a known working version?   Then version is updated as it's tested?

**Comment by Dhaiwat10** [comment]
@e-roy can you check now with the latest version?
