### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/create-dao#5]
Send in your user stories here so we can aggregate them

**Comment by berteotti** [comment]
I created a Google Spreadsheet with basic requirements. Feel free to comment and edit it.
[npx create-dao requirements link](https://docs.google.com/spreadsheets/d/1cj52LmFnG21AMfeZYlwjISPEEPPRkq1iBgnssj6ZfNY/edit?usp=sharing)

**Comment by naz3eh** [comment]
This spreadsheet is very nice and shows a clear workflow. Thanks for creating. 😄

**Comment by rheinardkorf** [comment]
@Dhaiwat10, @berteotti , I have now added this items to a new "Progress Board" so that they can easily be converted into issues and automated along the Kanban board.

@Dhaiwat10 , if you're happy with this, please close this issue. :)
